export const dataCTVN = [
  {
    id: 1,
    name: 'Tính điện áp',
    icon: require('../../assets/icons/iconTinhDienAp.png'),
    naviga: 'TinhDienAp',
    pro: false,
  },
  {
    id: 2,
    name: 'Tính dòng điện',
    icon: require('../../assets/icons/iconTinhDongDien.png'),
    naviga: 'TinhDongDien',
    pro: false,
  },

  {
    id: 3,
    name: 'Tính công suất hữu dụng',
    icon: require('../../assets/icons/iconTinhCongSuatHuuDung.png'),
    naviga: 'TinhCongSuatHuuDung',
    pro: false,
  },
  {
    id: 4,
    name: 'Tính công suất phản kháng',
    icon: require('../../assets/icons/iconTinhCongXuatPhanKhang.png'),
    naviga: 'TinhCongSuatPhanKhang',
    pro: false,
  },
  {
    id: 5,
    name: 'Tính công suất biểu kiến',
    icon: require('../../assets/icons/iconTinhCongSuatBieuKien.png'),
    naviga: 'TinhCongSuatBieuKien',
    pro: false,
  },
  {
    id: 6,
    name: 'Tính hệ số công suất',
    icon: require('../../assets/icons/iconTinhHeSoCongSuat.png'),
    naviga: 'TinhHeSoCongSuat',
    pro: false,
  },
  {
    id: 7,
    name: 'Tính điện trở',
    icon: require('../../assets/icons/iconTinhDienTro.png'),
    naviga: 'TinhDienTro',
    pro: false,
  },
  {
    id: 8,
    name: 'Tính điện kháng',
    icon: require('../../assets/icons/iconTinhDienTro.png'),
    naviga: 'TinhDienKhang',
    pro: false,
  },
  {
    id: 9,
    name: 'Tính toán sụt áp',
    icon: require('../../assets/icons/iconSutAp.png'),
    naviga: 'TinhToanSutAp',
    pro: false,
  },
  {
    id: 10,
    name: 'Chọn dây và cáp trên không',
    icon: require('../../assets/icons/iconChonDayVaCapTrenKhong.png'),
    naviga: 'Chondayvacaptrenkhong',
    pro: false,
  },
  {
    id: 11,
    name: 'Tính chọn cáp ngầm',
    icon: require('../../assets/icons/iconTinhChonCapNgam.png'),
    naviga: 'Tinhchoncapngam',
    pro: false,
  },
  {
    id: 12,
    name: 'Tính toán chiếu sáng',
    icon: require('../../assets/iconCT/tinhtoanchieusang.png'),
    naviga: 'TinhToanChieuSang',
    pro: true,
  },
  {
    id: 13,
    name: 'Tính cáp trung thế',
    icon: require('../../assets/iconCT/tinhcaptrungthe.png'),
    naviga: 'TinhCapTrungThe',
    pro: true,
  },
  {
    id: 14,
    name: 'Tính thiết bị trung thế',
    icon: require('../../assets/iconCT/tinhthietbitrungthe.png'),
    naviga: 'TinhThietBiTrungThe',
    pro: true,
  },
  {
    id: 15,
    name: 'Tính chọn MBA',
    icon: require('../../assets/iconCT/tinhmaybienap.png'),
    naviga: 'TinhchonMBA',
    pro: true,
  },
  {
    id: 16,
    name: 'Tính cáp hạ thế sau MBA',
    icon: require('../../assets/icons/iconTinhCapHaTheSauMBA.png'),
    naviga: 'TinhcaphathesauMBA',
    pro: true,
  },
  {
    id: 17,
    name: 'Chọn TB tủ điện hạ thế tổng',
    icon: require('../../assets/icons/iconChonTbTuDienHaTheTong.png'),
    naviga: 'ChonTBtudienhathetong',
    pro: true,
  },
  {
    id: 18,
    name: 'Tính chọn bộ tụ bù',
    icon: require('../../assets/icons/iconTinhChonBoTuBu.png'),
    naviga: 'Tinhchonbotubu',
    pro: true,
  },
  {
    id: 19,
    name: 'Tính chọn aptomat',
    icon: require('../../assets/icons/iconTinhChonAptomat.png'),
    naviga: 'TinhChonCapVaAptomat',
    pro: true,
  },
  {
    id: 20,
    name: 'Tính ngắn mạch',
    icon: require('../../assets/iconCT/tinhnganmach.png'),
    naviga: 'TinhNganMach',
    pro: true,
  },
  {
    id: 21,
    name: 'Tính bán kính kim thu sét',
    icon: require('../../assets/icons/iconTinhBanKinhThuSet.png'),
    naviga: 'TinhTiepDiaChongSet',
    pro: true,
  },
  {
    id: 22,
    name: 'Tính tiếp địa nối đất',
    icon: require('../../assets/icons/iconTinhTiepDiaNoiDat.png'),
    naviga: 'Tinhtiepdianoidat',
    pro: true,
  },
  {
    id: 23,
    name: 'Bóc khối lượng chiếu sáng',
    icon: require('../../assets/icons/iconBocKhoiLuongChieuSang.png'),
    naviga: 'BocKhoiLuongChieuSang',
    pro: true,
  },
  {
    id: 24,
    name: 'Bóc khối lượng ổ cắm',
    icon: require('../../assets/icons/iconBocKhoiLuongOCam.png'),
    naviga: 'BocKhoiLuongOCam',
    pro: true,
  },
];

export const dataCTEN = [
  {
    id: 1,
    name: 'Demo Tiếng anh',
    icon: require('../../assets/icons/iconTinhDienAp.png'),
    naviga: 'TinhDienAp',
    pro: false,
  },
  {
    id: 2,
    name: 'Tính dòng điện',
    icon: require('../../assets/icons/iconTinhDongDien.png'),
    naviga: 'TinhDongDien',
    pro: false,
  },

  {
    id: 3,
    name: 'Tính công suất hữu dụng',
    icon: require('../../assets/icons/iconTinhCongSuatHuuDung.png'),
    naviga: 'TinhCongSuatHuuDung',
    pro: false,
  },
  {
    id: 4,
    name: 'Tính công suất phản kháng',
    icon: require('../../assets/icons/iconTinhCongXuatPhanKhang.png'),
    naviga: 'TinhCongSuatPhanKhang',
    pro: false,
  },
  {
    id: 5,
    name: 'Tính công suất biểu kiến',
    icon: require('../../assets/icons/iconTinhCongSuatBieuKien.png'),
    naviga: 'TinhCongSuatBieuKien',
    pro: false,
  },
  {
    id: 6,
    name: 'Tính hệ số công suất',
    icon: require('../../assets/icons/iconTinhHeSoCongSuat.png'),
    naviga: 'TinhHeSoCongSuat',
    pro: false,
  },
  {
    id: 7,
    name: 'Tính điện trở',
    icon: require('../../assets/icons/iconTinhDienTro.png'),
    naviga: 'TinhDienTro',
    pro: false,
  },
  {
    id: 8,
    name: 'Tính điện kháng',
    icon: require('../../assets/icons/iconTinhDienTro.png'),
    naviga: 'TinhDienKhang',
    pro: false,
  },
  {
    id: 9,
    name: 'Tính toán sụt áp',
    icon: require('../../assets/icons/iconSutAp.png'),
    naviga: 'TinhToanSutAp',
    pro: false,
  },
  {
    id: 10,
    name: 'Chọn dây và cáp trên không',
    icon: require('../../assets/icons/iconChonDayVaCapTrenKhong.png'),
    naviga: 'Chondayvacaptrenkhong',
    pro: false,
  },
  {
    id: 11,
    name: 'Tính chọn cáp ngầm',
    icon: require('../../assets/icons/iconTinhChonCapNgam.png'),
    naviga: 'Tinhchoncapngam',
    pro: false,
  },
  {
    id: 12,
    name: 'Tính toán chiếu sáng',
    icon: require('../../assets/iconCT/tinhtoanchieusang.png'),
    naviga: 'TinhToanChieuSang',
    pro: true,
  },
  {
    id: 13,
    name: 'Tính cáp trung thế',
    icon: require('../../assets/iconCT/tinhcaptrungthe.png'),
    naviga: 'TinhCapTrungThe',
    pro: true,
  },
  {
    id: 14,
    name: 'Tính thiết bị trung thế',
    icon: require('../../assets/iconCT/tinhthietbitrungthe.png'),
    naviga: 'TinhThietBiTrungThe',
    pro: true,
  },
  {
    id: 15,
    name: 'Tính chọn MBA',
    icon: require('../../assets/iconCT/tinhmaybienap.png'),
    naviga: 'TinhchonMBA',
    pro: true,
  },
  {
    id: 16,
    name: 'Tính cáp hạ thế sau MBA',
    icon: require('../../assets/icons/iconTinhCapHaTheSauMBA.png'),
    naviga: 'TinhcaphathesauMBA',
    pro: true,
  },
  {
    id: 17,
    name: 'Chọn TB tủ điện hạ thế tổng',
    icon: require('../../assets/icons/iconChonTbTuDienHaTheTong.png'),
    naviga: 'ChonTBtudienhathetong',
    pro: true,
  },
  {
    id: 18,
    name: 'Tính chọn bộ tụ bù',
    icon: require('../../assets/icons/iconTinhChonBoTuBu.png'),
    naviga: 'Tinhchonbotubu',
    pro: true,
  },
  {
    id: 19,
    name: 'Tính chọn aptomat',
    icon: require('../../assets/icons/iconTinhChonAptomat.png'),
    naviga: 'TinhChonCapVaAptomat',
    pro: true,
  },
  {
    id: 20,
    name: 'Tính ngắn mạch',
    icon: require('../../assets/iconCT/tinhnganmach.png'),
    naviga: 'TinhNganMach',
    pro: true,
  },
  {
    id: 21,
    name: 'Tính bán kính kim thu sét',
    icon: require('../../assets/icons/iconTinhBanKinhThuSet.png'),
    naviga: 'TinhTiepDiaChongSet',
    pro: true,
  },
  {
    id: 22,
    name: 'Tính tiếp địa nối đất',
    icon: require('../../assets/icons/iconTinhTiepDiaNoiDat.png'),
    naviga: 'Tinhtiepdianoidat',
    pro: true,
  },
  {
    id: 23,
    name: 'Bóc khối lượng chiếu sáng',
    icon: require('../../assets/icons/iconBocKhoiLuongChieuSang.png'),
    naviga: 'BocKhoiLuongChieuSang',
    pro: true,
  },
  {
    id: 24,
    name: 'Bóc khối lượng ổ cắm',
    icon: require('../../assets/icons/iconBocKhoiLuongOCam.png'),
    naviga: 'BocKhoiLuongOCam',
    pro: true,
  },
];
