const dataCT = [
  {
    id: 1,
    name: 'Chuyển đổi tiết diện',
    icon: require('../../assets/iconCT/CT.png'),
    img: require('../../assets/images/1.png'),
  },
  {
    id: 2,
    name: 'Chuyển đổi sao- tam giác',
    icon: require('../../assets/iconCT/CT.png'),
    img: require('../../assets/images/2.png'),
  },
  {
    id: 3,
    name: 'Chuyển đổi Ah / kWh',
    icon: require('../../assets/iconCT/CT.png'),
    img: require('../../assets/images/3.png'),
  },
  {
    id: 4,
    name: 'Chuyển đổi nhiệt độ',
    icon: require('../../assets/iconCT/CT.png'),
    img: require('../../assets/images/4.png'),
  },
  {
    id: 5,
    name: 'Chuyển đổi Var / uF',
    icon: require('../../assets/iconCT/CT.png'),
    img: require('../../assets/images/5.png'),
  },
  {
    id: 6,
    name: 'Chuyển đổi tốc độ',
    icon: require('../../assets/iconCT/CT.png'),
    img: require('../../assets/images/6.png'),
  },
  {
    id: 7,
    name: 'Chuyển đổi góc',
    icon: require('../../assets/iconCT/CT.png'),
    img: require('../../assets/images/7.png'),
  },
  {
    id: 8,
    name: 'Chức năng lượng giác',
    icon: require('../../assets/iconCT/CT.png'),
    img: require('../../assets/images/8.png'),
  },
  {
    id: 9,
    name: 'Mô-men xoắn',
    icon: require('../../assets/iconCT/CT.png'),
    img: require('../../assets/images/9.png'),
  },
  {
    id: 10,
    name: 'Độ trượt động cơ',
    icon: require('../../assets/iconCT/CT.png'),
    img: require('../../assets/images/10.png'),
  },
  {
    id: 11,
    name: 'Tốc độ động cơ',
    icon: require('../../assets/iconCT/CT.png'),
    img: require('../../assets/images/11.png'),
  },
  {
    id: 12,
    name: 'Hiệu suất động cơ',
    icon: require('../../assets/iconCT/CT.png'),
    img: require('../../assets/images/12.png'),
  },
  {
    id: 13,
    name: 'Tụ khởi động của động cơ',
    icon: require('../../assets/iconCT/CT.png'),
    img: require('../../assets/images/13.png'),
  },
  {
    id: 14,
    name: 'Dòng ngắn mạch trạm',
    icon: require('../../assets/iconCT/CT.png'),
    img: require('../../assets/images/14.png'),
  },
  {
    id: 15,
    name: 'Dòng ngắn mạch tối thiểu',
    icon: require('../../assets/iconCT/CT.png'),
    img: require('../../assets/images/15.png'),
  },
  {
    id: 16,
    name: 'Dòng ngắn mạch tối đa',
    icon: require('../../assets/iconCT/CT.png'),
    img: require('../../assets/images/16.png'),
  },
  {
    id: 17,
    name: 'Cuộn dây sơ cấp và thứ cấp máy biến áp',
    icon: require('../../assets/iconCT/CT.png'),
    img: require('../../assets/images/17.png'),
  },
  {
    id: 18,
    name: 'Hệ thống đối đất',
    icon: require('../../assets/iconCT/CT.png'),
    img: require('../../assets/images/18.png'),
  },
  {
    id: 19,
    name: 'Năng lượng tụ điện ở điện áp khác nhau',
    icon: require('../../assets/iconCT/CT.png'),
    img: require('../../assets/images/19.png'),
  },
  {
    id: 20,
    name: 'Hiệu chỉnh hệ số công suất của máy biến áp MV-LV',
    icon: require('../../assets/iconCT/CT.png'),
    img: require('../../assets/images/20.png'),
  },
  {
    id: 21,
    name: 'Hiệu chỉnh hệ số công suất',
    icon: require('../../assets/iconCT/CT.png'),
    img: require('../../assets/images/21.png'),
  },
  {
    id: 22,
    name: 'Bộ chia dòng điện',
    icon: require('../../assets/iconCT/CT.png'),
    img: require('../../assets/images/22.png'),
  },
  {
    id: 23,
    name: 'Bộ chia điện áp',
    icon: require('../../assets/iconCT/CT.png'),
    img: require('../../assets/images/23.png'),
  },
  {
    id: 24,
    name: 'Tần số góc - vận tốc góc',
    icon: require('../../assets/iconCT/CT.png'),
    img: require('../../assets/images/24.png'),
  },
  {
    id: 25,
    name: 'Trở kháng từ điện trở và điện kháng',
    icon: require('../../assets/iconCT/CT.png'),
    img: require('../../assets/images/25.png'),
  },
  {
    id: 26,
    name: 'Điện kháng',
    icon: require('../../assets/iconCT/CT.png'),
    img: require('../../assets/images/26.png'),
  },
  {
    id: 27,
    name: 'Dòng hoạt động',
    icon: require('../../assets/iconCT/CT.png'),
    img: require('../../assets/images/27.png'),
  },
  {
    id: 28,
    name: 'Chọn aptomat',
    icon: require('../../assets/iconCT/CT.png'),
    img: require('../../assets/images/28.png'),
  },
  {
    id: 29,
    name: 'Tổng trở',
    icon: require('../../assets/iconCT/CT.png'),
    img: require('../../assets/images/29.png'),
  },
  {
    id: 30,
    name: 'Tổng tụ',
    icon: require('../../assets/iconCT/CT.png'),
    img: require('../../assets/images/30.png'),
  },
  {
    id: 31,
    name: 'Trở suất',
    icon: require('../../assets/iconCT/CT.png'),
    img: require('../../assets/images/31.png'),
  },
  {
    id: 32,
    name: 'Tính toán nhiệt độ dây dẫy',
    icon: require('../../assets/iconCT/CT.png'),
    img: require('../../assets/images/32.png'),
  },
  {
    id: 33,
    name: 'Khả năng chịu dòng của thanh cái',
    icon: require('../../assets/iconCT/CT.png'),
    img: require('../../assets/images/33.png'),
  },
  {
    id: 34,
    name: 'Chiều dài dây dẫn tối đa',
    icon: require('../../assets/iconCT/CT.png'),
    img: require('../../assets/images/34.png'),
  },
  {
    id: 35,
    name: 'Sụt áp',
    icon: require('../../assets/iconCT/CT.png'),
    img: require('../../assets/images/35.png'),
  },
  {
    id: 36,
    name: 'Cỡ dây và cáp',
    icon: require('../../assets/iconCT/CT.png'),
    img: require('../../assets/images/36.png'),
  },
  {
    id: 37,
    name: 'Hệ số công suất',
    icon: require('../../assets/iconCT/CT.png'),
    img: require('../../assets/images/37.png'),
  },
  {
    id: 38,
    name: 'Công suất biểu kiến',
    icon: require('../../assets/iconCT/CT.png'),
    img: require('../../assets/images/38.png'),
  },
  {
    id: 39,
    name: 'Công suất phản kháng',
    icon: require('../../assets/iconCT/CT.png'),
    img: require('../../assets/images/39.png'),
  },
  {
    id: 40,
    name: 'Công suất tác dụng',
    icon: require('../../assets/iconCT/CT.png'),
    img: require('../../assets/images/40.png'),
  },
  {
    id: 41,
    name: 'Trở kháng',
    icon: require('../../assets/iconCT/CT.png'),
    img: require('../../assets/images/41.png'),
  },
  {
    id: 42,
    name: 'Điện trở',
    icon: require('../../assets/iconCT/CT.png'),
    img: require('../../assets/images/42.png'),
  },
  {
    id: 43,
    name: 'Điện áp',
    icon: require('../../assets/iconCT/CT.png'),
    img: require('../../assets/images/43.png'),
  },
  {
    id: 44,
    name: 'Công suất',
    icon: require('../../assets/iconCT/CT.png'),
    img: require('../../assets/images/44.png'),
  },
  {
    id: 45,
    name: 'Dòng điện',
    icon: require('../../assets/iconCT/CT.png'),
    img: require('../../assets/images/45.png'),
  },
  {
    id: 46,
    name: 'Định luật Ohm thứ nhất',
    icon: require('../../assets/iconCT/CT.png'),
    img: require('../../assets/images/46.png'),
  },
  {
    id: 47,
    name: 'Định luật Ohm thứ hai',
    icon: require('../../assets/iconCT/CT.png'),
    img: require('../../assets/images/47.png'),
  },
];
export default dataCT;
